PREFIX_TAGS = "@"

TAG_NAME        = PREFIX_TAGS + "NAME"
TAG_TAG         = PREFIX_TAGS + "TAG"
TAG_LEVEL       = PREFIX_TAGS + "LEVEL"
TAG_PRIO        = PREFIX_TAGS + "PRIO"
TAG_FEATURES    = PREFIX_TAGS + "FEATURES"
TAG_TESTNUMBER  = PREFIX_TAGS + "TN"
TAG_DEPENDS     = PREFIX_TAGS + "DEPENDS"
TAG_ON_SUCCESS  = PREFIX_TAGS + "ON_SUCCESS"
TAG_ON_FAILURE  = PREFIX_TAGS + "ON_FAILURE"

STATE_PASSED            = "PASS"
STATE_SKIPPED           = "SKIP"
STATE_FAILED            = "FAIL"
STATE_FAILED_KNOWN_BUG  = "FAIL_BUG"
SEVERITY_STATES_ORDER = [STATE_FAILED, STATE_FAILED_KNOWN_BUG, STATE_SKIPPED, STATE_PASSED]
